import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

const baseURL =
  "https://yifgzyyqlpgydlzwcsaj.supabase.in/storage/v1/object/public/calm-shop-books/";

export const products = [
  {
    _id: uuid(),
    title: "1984",
    author: "George Orwell",
    actualPrice: "300",
    discountedPrice: "222",
    off: "26",
    categoryName: "fiction",
    path: `${baseURL}1984.jpg`,
    rating: 2,
  },
  {
    _id: uuid(),
    title: "A short history of the World",
    author: "Wells H.G.",
    actualPrice: "299",
    discountedPrice: "135",
    off: "55",
    categoryName: "history",
    path: `${baseURL}a-short-history-of-time.jpg`,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "The Alchemist",
    author: "Paulo Coehlo",
    actualPrice: "248",
    discountedPrice: "186",
    off: "25",
    categoryName: "fiction",
    path: `${baseURL}alchemist.jpg`,
    rating: 5,
  },
  {
    _id: uuid(),
    title: "Alexander: The Great",
    author: "Abbott Jacob",
    actualPrice: "150",
    discountedPrice: "90",
    off: "40",
    categoryName: "history",
    path: `${baseURL}alexander.jpg`,
    rating: 2,
  },
  {
    _id: uuid(),
    title: "The Art of War",
    author: "Tzu Sun",
    actualPrice: "149",
    discountedPrice: "70",
    off: "53",
    categoryName: "history",
    path: `${baseURL}art-of-war.jpg`,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Beyond Good and Evil",
    author: "Nietzsche Friedrich",
    actualPrice: "125",
    discountedPrice: "85",
    off: "32",
    categoryName: "philosophy",
    path: `${baseURL}beyond-good-and-evil.jpg`,
    rating: 3,
  },
  {
    _id: uuid(),
    title: "Metamorphosis",
    author: "Kafka Franz",
    actualPrice: "177",
    discountedPrice: "69",
    off: "61",
    categoryName: "fiction",
    path: `${baseURL}metamorphosis.jpg`,
    rating: 2,
  },
  {
    _id: uuid(),
    title: "Sapiens",
    author: "Harari Yuval Noah",
    actualPrice: "499",
    discountedPrice: "290",
    off: "42",
    categoryName: "history",
    path: `${baseURL}sapiens.jpg`,
    rating: 1,
  },
  {
    _id: uuid(),
    title: "The Importance of Being Earnest",
    author: "Wilde Oscar",
    actualPrice: "75",
    discountedPrice: "53",
    off: "30",
    categoryName: "fiction",
    path: `${baseURL}the-importance-of-being-earnest.jpg`,
    rating: 5,
  },
  {
    _id: uuid(),
    title: "The Origin of Species",
    author: "Charles Darwin",
    actualPrice: "269",
    discountedPrice: "121",
    off: "55",
    categoryName: "history",
    path: `${baseURL}the-origin-of-species.jpg`,
    rating: 2,
  },
  {
    _id: uuid(),
    title: "The Politics",
    author: "Aristotle",
    actualPrice: "199",
    discountedPrice: "106",
    off: "47",
    categoryName: "political-science",
    path: `${baseURL}the-politics.jpg`,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "The Republic",
    author: "Plato",
    actualPrice: "199",
    discountedPrice: "106",
    off: "47",
    categoryName: "history",
    path: `${baseURL}the-republic.jpg`,
    rating: 3,
  },
  {
    _id: uuid(),
    title: "War and Peace",
    author: "Leo Tolstoy",
    actualPrice: "499",
    discountedPrice: "370",
    off: "26",
    categoryName: "fiction",
    path: `${baseURL}war-and-peace.jpg`,
    rating: 1,
  },
  {
    _id: uuid(),
    title: "Wealth of Nations",
    author: "Adam Smith",
    actualPrice: "399",
    discountedPrice: "195",
    off: "49",
    categoryName: "political-science",
    path: `${baseURL}wealth-of-nations.jpg`,
    rating: 4,
  },
  {
    _id: uuid(),
    title: "Wuthering Heights",
    author: "Bronte Emily",
    actualPrice: "199",
    discountedPrice:"102",
    off: "49",
    categoryName: "fiction",
    path: `${baseURL}wuthering-heights.jpg`,
    rating: 2,
  },
];
